### ISSUE TITLE
Prefix the commands with `File Manager:` instead of just `File:` (discussion/suggestion)

### ISSUE THREAD

**Issue by evandrocoan** [math2001/FileManager#1]
### Prefix the commands with `File Manager:` instead of just `File:` (discussion/suggestion)

This new we can easily find this package commands and do not mix them with other packages as SidebarEnhancement and AdvancedNewFile.

[FileManager.sublime-commands](https://github.com/math2001/FileManager/files/601828/FileManager.txt)

**Comment by math2001** [comment]
Why would you want to keep SidebarEnhancement ? What do you want to keep from it? Because the point was to replace it (with AdvancedNewFile)

**Comment by evandrocoan** [comment]
I would like to keep both to be sure I am not losing any functionality.

I would have to take some time to process exactly is going on here in. With this package I am interested on the autocompletion which seems to be promising.

**Comment by math2001** [comment]
> I would like to keep both to be sure I am not losing any functionality.

You're going to have some duplicated features then...

When I said *What do you want to keep from it?*, I meant what **features** did you want to keep from SidebarEnhancement. Because SidebarEnhancement is messy (for me), so if there is anything that you'd like to see if FM and I'll probably add it.

If you want to try something, disable SidebarEnhancement and see what you feel I need to add to FM.

But, if you really want to keep both, then I'll prefix FM's commands with `File Manager:`

**Comment by evandrocoan** [comment]
> When I said What do you want to keep from it?

I understood it, I just need to:

>I would have to take some time to process exactly is going on here in.

Luckily it would take like a day maybe. Or week, month and on the worst case, a year. This depends on my free time, work load and development aim. As they are constantly changing I cannot to be sure exactly when I am going to be ready/able to precisely answer your question:

> Why would you want to keep SidebarEnhancement ? What do you want to keep from it?

**Comment by kapooostin** [comment]
I think proper namespacing is necessary, especially while your package is in development.

**Comment by math2001** [comment]
oh, yes, you're right. I'll change it in the next release.

**Comment by math2001** [comment]
All right, it's done.

You might need to remove and reinstall `FileManager` to get the modification (after a few unsuccessful tests, I'm not sure if package control check if the added repository have been updated)
