### ISSUE TITLE
fm_create_file_from_selection OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by unknownuser88** [math2001/FileManager#11]
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/2427559/23698060/90e227a2-0403-11e7-8ee3-7bab8501fea0.gif)

it show all selection in context menu and when I click on it it gives me an error 

```
Traceback (most recent call last):
  File "/home/username/Desktop/sublime_text_3/sublime_plugin.py", line 780, in run_
    return self.run(**args)
  File "FMcommands.create in /home/username/.config/sublime-text-3/Installed Packages/FileManager.sublime-package", line 18, in run
OSError: [Errno 36] File name too long: ' : [];\n        File.progress = File.progress || 0;\n        this.progress = 0;\n        this.object = object;\n        this.url = url;\n .....
```

looks like it try to set filename all selection 
when selection is short it open new blank file saved on disk (name of file the text I select)

**Comment by math2001** [comment]
Oops, yep, that's bad. 😕  And easy thing to check would be the `\n` (if there's any, don't show). I'll fix that soon! ⏲ 

Note: please put your multiline code between ```, like this:

    ```
    code
    code
    ```
