### ISSUE TITLE
New file relative to current open file.

### ISSUE THREAD

**Issue by aristidesfl** [math2001/FileManager#17]
Is it possible to make the shortcut ⌥N create a new file relative to the current open file, instead of root folder?

Similar to SideBarEnhancements [New File relative to current view](https://github.com/SideBarEnhancements-org/SideBarEnhancements/blob/st3/Commands.sublime-commands#L7)

**Comment by math2001** [comment]
Yes, it is. You just have to use the `$here` alias. Have a look here: https://github.com/math2001/FileManager/issues/16#issuecomment-308361859

**Comment by aristidesfl** [comment]
👍  Maybe this should go into the readme :)
