### ISSUE TITLE
How to rename file and leave it in the same place?

### ISSUE THREAD

**Issue by kapooostin** [math2001/FileManager#2]
When I try to **`File: Rename`**, I get an error alert ```The path `create_from` does not exist``` and the file is moved to a subfolder `path\to\file\plus\absolute\path\to\file\once\again\`.

**Comment by kapooostin** [comment]
OSX 10.10.5, SLT 3125

**Comment by math2001** [comment]
This is weird. Are you sure that your path exists? Copy the path, open the sublime text console and paste this in:

`import os.path; print(os.path.isidr('<your path>'))`

You should see `True` printed out.

**Comment by kapooostin** [comment]
I try to rename an open file, not to move it. So it does exist.

**Comment by kapooostin** [comment]
Your command returns an error `AttributeError: 'module' object has no attribute 'isidr'`

**Comment by math2001** [comment]
I made an update so that it raises an error when there is an error message (so it won't move your file if there is an error).

Can you retry and tell me what you see in the console please?

**Comment by math2001** [comment]
@kapooostin is your problem now solved?

**Comment by kapooostin** [comment]
I have not tried it yet.

**Comment by kapooostin** [comment]
Yes. It renames now alright, thank you!
