### ISSUE TITLE
The Open in Browser doesn't work

### ISSUE THREAD

**Issue by gusbemacbe** [math2001/FileManager#21]
### Description

I can't open the browser to click the file and select “Open in Browser”. 

### Steps to Reproduce
1. You click the file inside editor or in the sidebar
2. Select “Open in Browser”
3. Nothing happened and it didn't open the browser.

### Versions

* Sublime Text 3143
* macOS High Sierra 10.13.1
* I use the latest versions of Google Chrome Canary, Brave or Firefox Developer Edition as default browsers.

**Comment by bazuzu931** [comment]
+,
Instead it's open file as sublime tab)) This browser select mean sublime browser view)

**Comment by math2001** [comment]
> Instead it's open file as sublime tab)) This browser select mean sublime browser view)

What it does (at least one windows) is run the default app for the file you're trying to open. So, for example, if you open a folder in the browser, it'll actually open the folder in the Explorer. I'm guessing it's the same for MacOS

@gusbemacbe what kind of file are you trying to open. Is there anything happening (in the console for example - `View -> Show Console`)?

**Comment by bazuzu931** [comment]
I have got a last version of  sublime, linux mint and google-chrome by default.
but after choosing `open in browser`  it opens only as a sublime tab without showing in a chrome browser.
i have  tried to open html file.
there is nothing in the console.

**Comment by gusbemacbe** [comment]
Hi @math2001 

Both HTML and PHP.

I have the same problem that Bazuzu has.

But after updating Sublime Text 3 version, I was able of opening the file in HTML.

**Comment by linkhanfeng** [comment]
open_in_browser.py

import urllib
path = urllib.parse.quote(path)

**Comment by samholmes** [comment]
I'm still experiencing this issue. What was the fix?

**Comment by bazuzu931** [comment]
> I'm experiencing this issue. What was the fix?

build 3176 its work
