### ISSUE TITLE
Command to use browser from current directory...

### ISSUE THREAD

**Issue by thezimmee** [math2001/FileManager#26]
Hello. Great plugin! I'm trying to add a key binding / command that browses files from the current directory. I have tried this:

```
{ "keys": ["super+o"], "command": "fm_create", "args": {
    "paths": ["${folder}"],
    "initial_text": "",
    "start_with_browser": true,
    "no_browser_action": true,
} },
```

and this:

```
{ "keys": ["super+o"], "command": "fm_create", "args": {
    "paths": ["."],
    "initial_text": "",
    "start_with_browser": true,
    "no_browser_action": true,
} },
```

to no avail. How would I do this?

**Comment by math2001** [comment]
Hum that's weird. sublime text doesn't allow me to map anything to `super+o`. I tried `ctrl+n` just as an example, and it worked somewhat as expected (it also didn't expand aliases, but it does now) :slightly_smiling_face:
