### ISSUE TITLE
Moving multiple files deletes without warning

### ISSUE THREAD

**Issue by dhelonious** [math2001/FileManager#28]
When multiple files are selected, the move command deletes all files after text input for the path. However, this only happens on my Linux machine. On Windows the behavior is as expected.

**Comment by henrique-smr** [comment]
I also experienced the same issue!!
Almost lost a lot of work!!

**Comment by sinasharifzade** [comment]
same here

**Comment by sharifzadesina** [comment]
Same here! this is a serious bug.

**Comment by TheSecEng** [comment]
Just referencing.

https://github.com/math2001/FileManager/pull/43

**Comment by math2001** [comment]
I couldn't reproduce this, but I'm seeing that the paths are now only using forward slashes on linux (and not backslashes like it use to). I'm going to trust @sharifzadesina, and assume that this solves it. Please re-open or create an other issue if this still occurs :slightly_smiling_face:
