### ISSUE TITLE
[macos?] bug when creating a folder and move a file just after

### ISSUE THREAD

**Issue by kud** [math2001/FileManager#35]
Hard to explain but.

When you create a folder, and just after try to move a file, the base path isn't correct and will move files INTO sublimetext.app folder.

![2019-02-26 18-34-57 2019-02-26 18_40_21](https://user-images.githubusercontent.com/655838/53434044-04655a80-39f6-11e9-9659-e18ad8f09961.gif)

A workaround is to create the folder, click on another file, click on the file you want to move, and choose "move".

**Comment by kud** [comment]
I've also got this problem when I want to move a bunch of files in the same time.

**Comment by kud** [comment]
Confirmed, when you select multiple files, it has a wrong path.

**Comment by math2001** [comment]
This should be fixed by #43 :slightly_smiling_face: . Please reopen if not.
