### ISSUE TITLE
Copy the current file's path keybinding [feature request]

### ISSUE THREAD

**Issue by nilscox** [math2001/FileManager#36]
Hi!

First of all, thank you for this awesome plugin!

I often want to copy the current file's (relative) path to the clipboard, which works like a charm using `left click -> copy -> relative path` on the file tree. However, I intend to minimize the usage of a mouse in my workflow, so I think a keybinding would be of great use for copying the relative / absolute path of the currently opened file.

As I looked over the docs, I couldn't find a way of binding this action to a keyboard shortcut. For now, I use [this plugin](https://packagecontrol.io/packages/Copy%20Relative%20Path) to achieve this, but is is possible to add this feature to FileManager?

**Comment by nilscox** [comment]
I actually found a way to copy the relative / absolute path and filename of the current file with existing commands from FileManager:

```
[
  { "keys": ["..."] , "command": "fm_copy", "args": { "which": "relative path" } },
  { "keys": ["..."] , "command": "fm_copy", "args": { "which": "absolute path" } },
  { "keys": ["..."] , "command": "fm_copy", "args": { "which": "name" } }
]
```

This could be added to the documentation. Hope it helps!

**Comment by danilokleber** [comment]
Is it possible to include the line number in the copied path?

**Comment by math2001** [comment]
I don't think that belongs in file manager, but it's not too hard to write your own plugin for that.

```python
import sublime
import sublime_plugin


class CopyFilePathAndLineNumberCommand(sublime_plugin.TextCommand):
	def run(self, edit):
		row_number = self.view.rowcol(self.view.sel()[0].begin())[0] + 1
		file_path = None

		for folder in self.view.window().folders():
			if folder in self.view.file_name():
				file_path = self.view.file_name().replace(folder + '/', '')
				break

		if file_path is None:
			file_path = self.view.file_name()

		sublime.set_clipboard('{}:{}'.format(file_path, row_number))

```

```json
{"keys": [...], "command": "copy_file_path_and_line_number"}
```
