### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by viktormaar** [math2001/FileManager#38]
Menuitems became missing from context menu. Right-clicking on a file or a folder makes many console errors like:

> Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 949, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/xxxx/Library/Application Support/Sublime Text 3/Installed Packages/FileManager.sublime-package/FMcommands/appcommand.py", line 9, in is_visible
  File "/Users/xxxx/Library/Application Support/Sublime Text 3/Installed Packages/FileManager.sublime-package/sublimefunctions.py", line 24, in get_settings
AttributeError: 'NoneType' object has no attribute 'load_settings'

Or the AttributeError sometimes is:

> AttributeError: 'NoneType' object has no attribute 'active_window'

OS: MacOS Mojave 10.14.4
Sublime version:  3.2.1 Build 3207

**Comment by math2001** [comment]
> AttributeError: 'NoneType' object has no attribute 'load_settings'

That's the `sublime` module not existing, which means it's trying to load the plugin too early, before the API is ready.

Same thing for the `AttributeError`, it's doing `sublime.active_window`, and `sublime` is None.

Have you tried restarting the editor? Do you still get that issue when this is the only plugin installed (how to temporary [revert to a fresh state](https://www.sublimetext.com/docs/3/revert.html))

**Comment by math2001** [comment]
Maybe you even just need to wait a bit for the API to load up. Do you still get those errors a minute after the editor has started?

**Comment by viktormaar** [comment]
Looks like it really was only a loading error. Simply closing and re-opening Sublime did not helped, but quiting (Cmd-Q) and restarting did.
Thank you for quick response!
