### ISSUE TITLE
aliases resolution is weird

### ISSUE THREAD

**Issue by kud** [math2001/FileManager#40]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/655838/62422195-e2f85100-b6ae-11e9-98b1-f787cbde6a37.png">

**Comment by math2001** [comment]
I think I saw it happen a few times on my linux machine, but after merging #43, I can't seem to be able to reproduce :slightly_smiling_face: 

I'm going to close this, but please reopen if you still have that bug.
