### ISSUE TITLE
Add to Package Control

### ISSUE THREAD

**Issue by ihodev** [math2001/FileManager#7]
Hi @math2001! Have you any plans to add it to the PC? 

P.S. Thanks for an awesome plugin :wink:

**Comment by math2001** [comment]
Whoo! This is so nice to hear! Thank you!

Hum, for now, not really... I want to test it for a while, see if there's some bugs, improve some commands (especially `create_from_selection`, I want it to auto-detect in python, php, js, not only HTML), and then maybe, yeah... 😄

**Comment by math2001** [comment]
Create from selection

- [x] python (might need some improvement, I'm kinda confused with relative/absolute import in python)
- [ ] php
- [ ] javascript
- [ ] ruby?

**Comment by math2001** [comment]
Here it is: <https://github.com/wbond/package_control_channel/pull/6051>

**Comment by math2001** [comment]
it's been merged in https://packagecontrol.io/packages/FileManager 😄
