### ISSUE TITLE
doesn't create folder if exists file with same name

### ISSUE THREAD

**Issue by unknownuser88** [math2001/FileManager#8]
if you create file with name abc then trying to create abc folder it doesn't work 
if there is no file abc it works fine

**Comment by math2001** [comment]
Yes, I'll fix this. Why did you close the issue though?

**Comment by unknownuser88** [comment]
because linux didn't allow you to create file and folder with same name

**Comment by math2001** [comment]
Oh, yes, sorry, I thought I sent this message: Windows doesn't allow it either...
