### ISSUE TITLE
can not duplicate the file to a new directory

### ISSUE THREAD

**Issue by devilmengcry** [math2001/FileManager#80]
```
File "./python3.8/shutil.py", line 435, in copy2
File "./python3.8/shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'xxx'
```

**Comment by math2001** [comment]
Please provide steps to reproduce

**Comment by devilmengcry** [comment]
![Jietu20220308-100807](https://user-images.githubusercontent.com/6964329/157152066-73f402b4-1949-4e90-b38b-5e264717061f.gif)
![image](https://user-images.githubusercontent.com/6964329/157152127-ed598961-f86a-40fd-9d5e-9933d4e3e300.png)
![image](https://user-images.githubusercontent.com/6964329/157152141-d07228d9-b715-4e08-99de-9f9a6601a17a.png)

**Comment by math2001** [comment]
Awesome thank you.
